# Generated by Django 4.0.5 on 2022-06-27 07:45

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
import zeon_media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('decription', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обращения')),
                ('callback_type', models.CharField(default='Обратный звонок', max_length=100, verbose_name='Тип обращения')),
                ('status_call', models.BooleanField(default=False, verbose_name='Позвонили?')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратные звонки',
            },
        ),
        migrations.CreateModel(
            name='Futer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('futer_image', models.ImageField(upload_to='futer_image', verbose_name='Фото для Футера')),
                ('heder_image', models.ImageField(upload_to='heder_image', verbose_name='Фото для Хедера')),
                ('information', models.TextField(verbose_name='Текстовая Информация')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
            },
        ),
        migrations.CreateModel(
            name='FuterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', multiselectfield.db.fields.MultiSelectField(choices=[('Number', 'Number'), ('Mail', 'Mail'), ('Telegram', 'Telegram'), ('WhatsApp', 'WhatsApp'), ('Instagram', 'Instagram')], db_index=True, default=('NUMBER', 'Number'), max_length=254, verbose_name='Выбор из списка')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='введенные данные')),
                ('num', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер')),
                ('whatsapp', models.CharField(blank=True, max_length=100, verbose_name='Whatsapp')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('mail', models.CharField(blank=True, max_length=100, verbose_name='Почта')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Ссылка футера',
                'verbose_name_plural': 'Ссылки футера',
            },
        ),
        migrations.CreateModel(
            name='HelpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='helpers_image', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': ' Вопрос и Ответ',
                'verbose_name_plural': 'Вопросы и Ответы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('descrintion', models.TextField(verbose_name='Описание')),
                ('images', models.ImageField(upload_to='news_image', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='OurAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='advantage_image', validators=[zeon_media.models.custom_validator], verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Наши преимущества',
                'verbose_name_plural': 'Наши преимущества',
            },
        ),
        migrations.CreateModel(
            name='PublicOffert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Публичная офферта',
                'verbose_name_plural': 'Публичная офферта',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlka', models.URLField(blank=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='slider_image', verbose_name='Фотография')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='zeon_media.slider')),
            ],
        ),
        migrations.CreateModel(
            name='Helpers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопросы')),
                ('answer', models.TextField(verbose_name='Ответы')),
                ('help', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='zeon_media.helpimage', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adout_us_image', models.ImageField(blank=True, null=True, upload_to='about_us')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us', to='zeon_media.aboutus')),
            ],
        ),
    ]
