# Generated by Django 4.0.5 on 2022-06-28 11:18

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Byer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер')),
                ('city', models.CharField(max_length=100, verbose_name='Страна')),
                ('country', models.CharField(max_length=100, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления')),
                ('choise', models.CharField(choices=[('New', 'Новый'), ('Ordered', 'Оформлен'), ('Deleted', 'Отменен')], default='Новый', max_length=50, verbose_name='Выбор из списка')),
            ],
            options={
                'verbose_name': 'Информация юзера',
                'verbose_name_plural': 'Информация юзера',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество линеек')),
                ('stock', models.IntegerField(verbose_name='Количество товара')),
                ('price', models.FloatField(verbose_name='Сумма')),
                ('sale', models.FloatField(verbose_name='Скидка')),
                ('final_price', models.FloatField(verbose_name='Итого к оплате')),
                ('byer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byer', to='cart.byer')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('color', colorfield.fields.ColorField(default=True, image_field=None, max_length=18, samples=None, verbose_name='Цвет')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('size', models.CharField(max_length=20, verbose_name='Размерный ряд')),
                ('old_price', models.IntegerField(verbose_name='Цена')),
                ('price', models.FloatField(verbose_name='Цена после скидки')),
                ('count', models.IntegerField(verbose_name='Количество товара')),
                ('byer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.order')),
            ],
            options={
                'verbose_name': 'Детализация заказа',
                'verbose_name_plural': 'Детализация заказа',
            },
        ),
    ]
