# Generated by Django 4.0.5 on 2022-06-27 07:45

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Коллекция')),
                ('images', models.ImageField(blank=True, null=True, upload_to='collction_image', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': ' Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('vendor_code', models.CharField(max_length=100, verbose_name='артикул')),
                ('old_price', models.IntegerField(default=True, verbose_name='старая цена')),
                ('sale', models.IntegerField(default=True, verbose_name='скидка')),
                ('price', models.IntegerField(blank=True, default=True, null=True, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='описание')),
                ('size', models.CharField(max_length=100, verbose_name='Размер')),
                ('stock', models.IntegerField(blank=True, default=True, null=True, verbose_name='Количество в линейке')),
                ('sostav', models.CharField(max_length=100, verbose_name='Состав')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('top_saled', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('new_product', models.BooleanField(default=False, verbose_name='Новинки')),
                ('favorites', models.BooleanField(default=False, verbose_name='Избранные')),
                ('collection_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.collections', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Фотография')),
                ('color', colorfield.fields.ColorField(default=True, image_field=None, max_length=18, samples=None, verbose_name='Цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CheckBocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='products.product')),
            ],
        ),
    ]
