# Generated by Django 4.0.5 on 2022-06-11 16:51

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Коллекция')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='collction_image')),
            ],
            options={
                'verbose_name': ' Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_saled', models.BooleanField(default=True, verbose_name='Хит продаж')),
                ('new_product', models.BooleanField(default=True, verbose_name='Новинки')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('vendor_code', models.CharField(max_length=100, verbose_name='артикул')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('old_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='старая цена')),
                ('sale', models.IntegerField(blank=True, default=0, verbose_name='скидка')),
                ('description', models.TextField(verbose_name='описание')),
                ('size', models.CharField(max_length=100, verbose_name='Размер')),
                ('stock', models.PositiveSmallIntegerField(default=True, verbose_name='Количество')),
                ('count', models.PositiveSmallIntegerField(default=True, verbose_name='Количество в линейке')),
                ('sostav', models.CharField(max_length=100, verbose_name='Состав')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.BooleanField(default=True, verbose_name='Избранные')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категоря')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.collections', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('color', colorfield.fields.ColorField(default=True, image_field=None, max_length=18, samples=None, verbose_name='Цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
